version: "3.5"
services:
  pisstaube:
    image: pisstaube
    build: ./
    volumes:
      - ./data/pisstaube_data/:/pisstaube/data
    depends_on:
      - datadog
      - db
      - elasticsearch
      - ipfs
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - DD_AGENT_HOST=datadog
      - MARIADB_USERNAME=root
      - MARIADB_PASSWORD=supersecretpasswordthatnobodywilleverknowsincenobodycanconencttothisdatabasepog
      - MARIADB_DATABASE=pisstaube
      - ELASTIC_HOSTNAME=elasticsearch
      - ELASTIC_PORT=9200
    env_file:
      - docker.env
    networks:
      - pisstaube_back
    restart: always
    ports:
      - 62011:5000

  elasticsearch:
    image: bitnami/elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - ELASTICSEARCH_HEAP_SIZE=2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - pisstaube_back
    volumes:
      - ./data/logs/elastic/:/var/log/elasticsearch/
      - ./config/elasticsearch/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200

  db:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql_data/:/var/lib/mysql
    restart: on-failure
    networks:
      - pisstaube_back
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpasswordthatnobodywilleverknowsincenobodycanconencttothisdatabasepog
      - MYSQL_ROOT_HOST=%
    expose:
      - 3306

  datadog:
    image: datadog/docker-dd-agent:latest
    depends_on:
      - elasticsearch
      - db
    env_file:
      - docker.env
    restart: on-failure
    networks:
      - pisstaube_back
    volumes:
      - ./data/logs/elastic/:/var/log/elasticsearch/
      - ./config/datadog/:/etc/dd-gent/conf.d/
    expose:
      - 8125
      - 8126

  ipfs:
    image: ipfs/go-ipfs:latest
    restart: on-failure
    networks:
      - pisstaube_back
    volumes:
      - ./data/ipfs_data/:/data/ipfs/
    expose:
      - 8080
      - 8081
      - 4001
      - 5001

networks:
  pisstaube_back:
    driver: bridge
