version: "3.5"
services:
  pisstaube:
    image: pisstaube
    build: ./
    volumes:
      - ./data/:/pisstaube/data
    links:
      - db
      - elasticsearch
    depends_on:
      - db
      - elasticsearch
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_USERNAME=root
      - MARIADB_PASSWORD=supersecretpasswordthatnobodywilleverknowsincenobodycanconencttothisdatabasepog
      - ELASTIC_HOSTNAME=elastic
      - ELASTIC_PORT=9200
    env_file:
      - docker.env
    restart: on-failure
    ports:
      - 62011:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - pisstaube_elastic_search_data:/usr/share/elasticsearch/data
    expose:
      - 9200

  db:
    container_name: db
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - pisstaube_mysql_data:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpasswordthatnobodywilleverknowsincenobodycanconencttothisdatabasepog
    expose:
      - 3306

volumes:
  pisstaube_mysql_data:
    driver: local
  pisstaube_elastic_search_data:
    driver: local
