init_config:

instances:
  - url: http://elasticsearch:9200
    cluster_stats: true # set true ONLY if you're not running the check on each cluster node
    pshard_stats: true # the agent sends primary shard metrics
    index_stats: true # the agent sends index level metrics
    pending_task_stats: true # the agent sends cluster-wide pending task metrics
    logs_enabled: true

logs:
  - type: file
    path: /var/log/elasticsearch/*.log
    source: elasticsearch
    service: pisstaube
